version: "3.8"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: skgu_diplome
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    container_name: migration_diplome
    build:
      context: .
      dockerfile: migration.dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "alembic upgrade head && echo 'Migration completed'"

  api:
    container_name: api_diplome
    build:
      context: .
      dockerfile: run_api.dockerfile
    depends_on:
      - migration
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: skgu_diplome
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./../skgu_site
      dockerfile: front.dockerfile
      args:
        REACT_APP_API_URL:  http://49.13.194.240:8000
    ports:
      - "3000:3000"
    depends_on:
      - api


volumes:
  db_data: