"""first

Revision ID: 3b90add845d4
Revises: 
Create Date: 2025-02-19 16:14:29.640920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b90add845d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floors',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('building_number', sa.String(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False, comment='Номер этажа'),
    sa.Column('image_data', sa.String(), nullable=False, comment='Изображение этажа в формате Base64'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edges',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('source_node_name', sa.String(), nullable=False, comment='Имя начального узла'),
    sa.Column('target_node_name', sa.String(), nullable=False, comment='Имя конечного узла'),
    sa.Column('weight', sa.Float(), nullable=True, comment='Вес ребра (расстояние, время и т.п.)'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor_id', 'source_node_name', 'target_node_name', name='unique_edge_per_floor')
    )
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='Уникальное имя узла на этаже'),
    sa.Column('x', sa.Float(), nullable=False, comment='Координата X узла'),
    sa.Column('y', sa.Float(), nullable=False, comment='Координата Y узла'),
    sa.Column('type', sa.String(), nullable=False, comment='Тип узла (office, corridor, etc.)'),
    sa.Column('name_ru', sa.String(), nullable=True, comment='Имя узла на русском'),
    sa.Column('name_en', sa.String(), nullable=True, comment='Имя узла на английском'),
    sa.Column('name_kz', sa.String(), nullable=True, comment='Имя узла на казахском'),
    sa.Column('description_ru', sa.String(), nullable=True, comment='Описание узла на русском'),
    sa.Column('description_en', sa.String(), nullable=True, comment='Описание узла на английском'),
    sa.Column('description_kz', sa.String(), nullable=True, comment='Описание узла на казахском'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor_id', 'name', name='unique_node_name_per_floor')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes')
    op.drop_table('edges')
    op.drop_table('floors')
    # ### end Alembic commands ###
