"""add new endpoints

Revision ID: 4a72f121b2ab
Revises: 96776a7453cb
Create Date: 2025-04-03 15:10:15.375763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a72f121b2ab'
down_revision = '96776a7453cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('important_links',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('link_text', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('important_links')
    # ### end Alembic commands ###
