"""new table events

Revision ID: 99d03dea7b7c
Revises: f2cb10d9bf9f
Create Date: 2025-04-07 17:31:40.525874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99d03dea7b7c'
down_revision = 'f2cb10d9bf9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_description', sa.String(), nullable=True))
    op.add_column('events', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('events', sa.Column('contact_email', sa.String(), nullable=True))
    op.alter_column('events', 'event_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'event_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('events', 'contact_email')
    op.drop_column('events', 'contact_phone')
    op.drop_column('events', 'event_description')
    # ### end Alembic commands ###
