"""users +-> password_no_hash

Revision ID: 23f1481ef4c8
Revises: 0f2cf222f199
Create Date: 2025-04-06 13:02:13.502334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f1481ef4c8'
down_revision = '0f2cf222f199'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_no_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_no_hash')
    # ### end Alembic commands ###
