"""add new endpoints

Revision ID: 96776a7453cb
Revises: 2155168741ab
Create Date: 2025-04-03 15:05:00.391296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96776a7453cb'
down_revision = '2155168741ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
