"""username -> login

Revision ID: 463d927eeade
Revises: daf590571eb1
Create Date: 2025-04-06 12:13:22.400891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463d927eeade'
down_revision = 'daf590571eb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.String(length=255), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
