"""add mind_file_path

Revision ID: d5a229e43807
Revises: 99d03dea7b7c
Create Date: 2025-04-20 11:33:48.755067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a229e43807'
down_revision = '99d03dea7b7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floors', sa.Column('mind_file_path', sa.String(), nullable=True, comment='Путь к .mind файлу'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('floors', 'mind_file_path')
    # ### end Alembic commands ###
