"""add address event

Revision ID: 202e763f789d
Revises: ae7ced81a999
Create Date: 2025-04-27 13:42:27.963780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202e763f789d'
down_revision = 'ae7ced81a999'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'address')
    # ### end Alembic commands ###
