"""new table events

Revision ID: f2cb10d9bf9f
Revises: 23f1481ef4c8
Create Date: 2025-04-07 17:26:02.205458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2cb10d9bf9f'
down_revision = '23f1481ef4c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_background', sa.String(), nullable=False),
    sa.Column('event_creator_name', sa.String(), nullable=False),
    sa.Column('event_creator_image', sa.String(), nullable=True),
    sa.Column('event_rating', sa.Float(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
