"""moderate

Revision ID: ae7ced81a999
Revises: d3c99b8cbcec
Create Date: 2025-04-26 14:23:36.871859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7ced81a999'
down_revision = 'd3c99b8cbcec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_moderate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_moderate')
    # ### end Alembic commands ###
