"""new model and user relatioships

Revision ID: d3c99b8cbcec
Revises: d3ef30b6d0ea
Create Date: 2025-04-24 22:11:19.991461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c99b8cbcec'
down_revision = 'd3ef30b6d0ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False, comment='Оценка от 1 до 5'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Текстовый комментарий отзыва'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания отзыва'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
