"""add new colums location

Revision ID: 2155168741ab
Revises: ebe0a132b6b1
Create Date: 2025-02-23 15:24:19.933865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2155168741ab'
down_revision = 'ebe0a132b6b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('building_type', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('building_type_name_ru', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'building_type_name_ru')
    op.drop_column('locations', 'building_type')
    # ### end Alembic commands ###
