"""add links

Revision ID: daf590571eb1
Revises: ed64222ce303
Create Date: 2025-04-06 12:12:09.377462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf590571eb1'
down_revision = 'ed64222ce303'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('important_links',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('link_text', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('important_links')
    # ### end Alembic commands ###
