"""add bounds table

Revision ID: ebe0a132b6b1
Revises: 079c12e71cb5
Create Date: 2025-02-21 12:27:35.480235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe0a132b6b1'
down_revision = '079c12e71cb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floors', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'floors', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'floors', type_='foreignkey')
    op.drop_column('floors', 'location_id')
    # ### end Alembic commands ###
