"""new model and user relatioships

Revision ID: d3ef30b6d0ea
Revises: 60779fc599c7
Create Date: 2025-04-24 22:10:27.730632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ef30b6d0ea'
down_revision = '60779fc599c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
